version: "3"

services:

  index_server:
    image: httpd:latest
    volumes:
      - ./index/public:/usr/local/apache2/htdocs
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
    networks:
      - web
    restart: always
    labels:
      - "traefik.backend=index_server"
      - "traefik.frontend.rule=Host:bradsease.com,www.bradsease.com"
      - "traefik.docker.network=web"
      - "traefik.port=80"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.frameDeny=True"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"

  ghost:
    image: ghost:latest
    restart: always
    volumes:
      - ./blog:/var/lib/ghost/content
    environment:
      - url=https://blog.bradsease.com
    networks:
      - web
    labels:
      - "traefik.backend=ghost"
      - "traefik.frontend.rule=Host:blog.bradsease.com"
      - "traefik.docker.network=web"
      - "traefik.port=2368"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.frameDeny=True"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"

networks:
  web:
    external: true
