version: "3"

services:

  index:
    image: nginxinc/nginx-unprivileged:latest
    volumes:
      - ./index/public:/usr/share/nginx/html:ro
      - ./index/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - web
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.personal_site_http.entrypoints=http
      - traefik.http.routers.personal_site_http.rule=Host(`www.bradsease.com`)
      - traefik.http.routers.personal_site_http.middlewares=ssl_redirect
      - traefik.http.routers.personal_site.entrypoints=https
      - traefik.http.routers.personal_site.rule=Host(`www.bradsease.com`)
      - traefik.http.routers.personal_site.middlewares=sts_headers
      - traefik.http.routers.personal_site.tls.certresolver=letsencrypt_tls
      - traefik.http.services.personal_site.loadbalancer.server.port=9090

networks:
  web:
    external: true
